//Session Constants
export const GET_TOKENS_LOADING = "GET_TOKENS_LOADING";
export const GET_TOKENS_SUCCESS = "GET_TOKENS_SUCCESS";
export const GET_TOKENS_FAIL = "GET_TOKENS_FAIL";

export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const SOCKET_AUTH_LOADING = "SOCKET_AUTH_LOADING";
export const SOCKET_AUTH_SUCCESS = "SOCKET_AUTH_SUCCESS";
export const SOCKET_AUTH_FAIL = "SOCKET_AUTH_FAIL";

export const SOCKET_REAUTH_LOADING = "SOCKET_AUTH_LOADING";
export const SOCKET_REAUTH_SUCCESS = "SOCKET_AUTH_SUCCESS";
export const SOCKET_REAUTH_FAIL = "SOCKET_AUTH_FAIL";

export const CONNECTED = "CONNECTED";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const CLEAR_SESSION = "CLEAR_SESSION";
