//Session Constants
export const SET_USERNAME = "SET_USERNAME";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_EXPIRATION = "SET_EXPIRATION";
export const SET_SOCKET_AUTH = "SET_SOCKET_AUTH";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAILED = "VERIFICATION_FAILED";
export const CLEAR_SESSION = "CLEAR_SESSION";

