export const GET_SPOTIFY_PROFILE = "GET_SPOTIFY_PROFILE";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";
export const SET_SOCKET_AUTH = "SET_SOCKET_AUTH";
export const SESSION_TIMED_OUT = "SESSION_TIMED_OUT";
export const TIMEOUT = 3600000;