export const SET_SPOTIFY_TOKENS = "SET_SPOTIFY_TOKENS";
export const GET_SPOTIFY_PROFILE = "GET_SPOTIFY_PROFILE";
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";
