export const SOCKET_AUTH_LOADING = "SOCKET_AUTH_LOADING";
export const SOCKET_AUTH_SUCCESS = "SOCKET_AUTH_SUCCESS";
export const SOCKET_AUTH_FAIL = "SOCKET_AUTH_FAIL";

export const SOCKET_REAUTH_LOADING = "SOCKET_REAUTH_LOADING";
export const SOCKET_REAUTH_SUCCESS = "SOCKET_REAUTH_SUCCESS";
export const SOCKET_REAUTH_FAIL = "SOCKET_REAUTH_FAIL";

export const CONNECTED = "CONNECTED";
export const DISCONNECTED = "DISCONNECTED";

export const SEND_SYNC = "SEND_SYNC";
export const RECIEVED_SYNC = "RECIEVED_SYNC";

export const SOCKET_CREATE_ROOM_LOADING = "SOCKET_CREATE_ROOM_LOADING";
export const SOCKET_CREATE_ROOM = "SOCKET_CREATE_ROOM";

export const SOCKET_LOG_OUT = "SOCKET_LOG_OUT";
